services:
  - type: web
    name: satistakip-panel
    env: node
    repo: https://github.com/yildirimtarhan/satistakip-panel
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
    autoDeploy: true
